site_name: Projectsveltos Documentation
copyright: Copyright © 2022 projectsveltos. All Rights Reserved.
site_description: 'Sveltos is a lightweight application designed to manage add-ons in hundreds of clusters. Projectsveltos extends functionality of Cluster API by providing a solution for managing the installation, 
configuration, upgrade, and deletion of kubernetes cluster add-ons using Helm charts and/or Kubernetes resource YAMLs. Projectsveltos supports multi-tenancy allowing platform admins to easily grant permissions 
to tenant admins.'
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
    - Projectsveltos: 'index.md'
    - Install: 'install.md'
    - Addon Distribution: 'addons.md'
    - Templates: 'template.md'
    - Drift detection: 'configuration_drift.md'
    - Multi-tenancy: 'multi-tenancy.md'
    - Cluster Classification: 'labels_management.md'
    - Snapshot: 'snapshot.md'
    - Register cluster: 'register-cluster.md'
    - Visibility: 'visibility.md'
    - Blogs and videos: 'blogs.md'
theme:
  features:
    - content.code.copy
    - search.share
    - navigation.tabs
    - navigation.tracking
    - navigation.footer
  name: material
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_url: https://github.com/projectsveltos
repo_name: projectsveltos
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/projectsveltos
      name: squidfunk on Twitter
      link: https://join.slack.com/t/projectsveltos/shared_invite/zt-1hraownbr-W8NTs6LTimxLPB8Erj8Q6Q
    - icon: fontawesome/brands/github
      link: https://github.com/projectsveltos
    - icon: fontawesome/brands/medium
      link: https://medium.com/@gianluca.mardente
    - icon: fontawesome/brands/product-hunt
      link: https://www.producthunt.com/products/projectsveltos